import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';
import { getSupabaseAdmin } from '@/lib/supabase/admin';

interface ReportMetrics {
  annualLaborSavings: number;
  annualHoursSaved: number;
  threeYearSavings: number;
  implementationCostLow: number;
  implementationCostHigh: number;
  paybackMonths: number | null;
  totalReadinessScore: number;
  maxReadinessScore: number;
}

interface ReportSummary {
  summary: string;
  bulletPoints: string[];
  quickWins?: string[];
}

interface ReportContext {
  industry: string;
  country: string;
  employeeCount: number;
  averageSalary: number;
  weeklyHours: number;
  aiMaturity: string;
  primaryGoal: string;
}

interface SendReportBody {
  email: string;
  locale: string;
  context: ReportContext;
  metrics: ReportMetrics;
  summary: ReportSummary;
}

const FROM = process.env.RESEND_FROM_EMAIL || 'WAZA <onboarding@resend.dev>';
const REPLY_TO = process.env.CALCULATOR_REPLY_TO || 'hello@wazalab.mx';

const money = (v: number) => '$' + Math.round(v).toLocaleString('en-US');
const hours = (v: number) => Math.round(v).toLocaleString('en-US');

function renderHtml({ email, context, metrics, summary, locale }: SendReportBody): string {
  const readinessPct = metrics.maxReadinessScore > 0
    ? Math.round((metrics.totalReadinessScore / metrics.maxReadinessScore) * 100)
    : 0;

  const labels = locale === 'es' ? {
    title: 'Tu reporte de preparación para IA',
    intro: 'Aquí está el resumen personalizado que generamos para tu negocio.',
    annualSavings: 'Ahorro anual estimado',
    annualHours: 'Horas recuperadas al año',
    threeYear: 'Ahorro a 3 años',
    implementation: 'Costo de implementación',
    payback: 'Periodo de retorno',
    paybackMonths: 'meses',
    readiness: 'Preparación para IA',
    focus: 'Áreas de enfoque',
    quickWins: 'Quick wins a 30 días',
    ctaTitle: '¿Quieres que lo construyamos?',
    ctaBody: 'Convertimos reportes como este en software funcional. Hablemos.',
    ctaButton: 'Agendar una consulta',
    footer: 'Este reporte fue generado por la Calculadora de ROI de IA de WAZA.',
  } : locale === 'de' ? {
    title: 'Ihr KI-Bereitschaftsbericht',
    intro: 'Hier ist die personalisierte Zusammenfassung für Ihr Unternehmen.',
    annualSavings: 'Geschätzte jährliche Einsparungen',
    annualHours: 'Wiedergewonnene Stunden pro Jahr',
    threeYear: '3-Jahres-Einsparungen',
    implementation: 'Implementierungskosten',
    payback: 'Amortisationszeit',
    paybackMonths: 'Monate',
    readiness: 'KI-Bereitschaft',
    focus: 'Fokusbereiche',
    quickWins: '30-Tage Quick Wins',
    ctaTitle: 'Wollen wir das bauen?',
    ctaBody: 'Wir verwandeln Berichte wie diesen in funktionierende Software. Sprechen wir.',
    ctaButton: 'Beratung vereinbaren',
    footer: 'Dieser Bericht wurde vom KI-ROI-Rechner von WAZA erstellt.',
  } : {
    title: 'Your AI Readiness Report',
    intro: 'Here\'s the personalized summary we generated for your business.',
    annualSavings: 'Estimated annual savings',
    annualHours: 'Hours reclaimed per year',
    threeYear: '3-year savings',
    implementation: 'Implementation cost',
    payback: 'Payback period',
    paybackMonths: 'months',
    readiness: 'AI readiness',
    focus: 'Focus areas',
    quickWins: '30-day quick wins',
    ctaTitle: 'Want this, shipped?',
    ctaBody: 'We turn reports like this into working software. Let\'s talk.',
    ctaButton: 'Book a consultation',
    footer: 'This report was generated by the WAZA AI ROI Calculator.',
  };

  return `<!doctype html>
<html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${labels.title}</title></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#111;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f5f5f5;padding:32px 16px;">
    <tr><td align="center">
      <table role="presentation" width="600" cellspacing="0" cellpadding="0" style="max-width:600px;background:#fff;border:1px solid #e5e5e5;border-radius:12px;overflow:hidden;">
        <tr><td style="padding:32px 32px 8px;">
          <div style="font-size:11px;letter-spacing:0.25em;text-transform:uppercase;color:#6b7280;font-weight:600;">WAZA · AI ROI</div>
          <h1 style="margin:12px 0 8px;font-size:28px;line-height:1.2;color:#000;font-weight:900;">${labels.title}</h1>
          <p style="margin:0;color:#4b5563;font-size:15px;line-height:1.55;">${labels.intro}</p>
        </td></tr>

        <tr><td style="padding:24px 32px;">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-top:1px solid #e5e5e5;border-bottom:1px solid #e5e5e5;">
            <tr>
              <td width="50%" style="padding:20px 16px;vertical-align:top;">
                <div style="font-size:10px;letter-spacing:0.25em;text-transform:uppercase;color:#6b7280;font-weight:600;">${labels.annualSavings}</div>
                <div style="margin-top:8px;font-size:28px;font-weight:900;color:#000;">${money(metrics.annualLaborSavings)}</div>
              </td>
              <td width="50%" style="padding:20px 16px;vertical-align:top;border-left:1px solid #e5e5e5;">
                <div style="font-size:10px;letter-spacing:0.25em;text-transform:uppercase;color:#6b7280;font-weight:600;">${labels.annualHours}</div>
                <div style="margin-top:8px;font-size:28px;font-weight:900;color:#000;">${hours(metrics.annualHoursSaved)}</div>
              </td>
            </tr>
            <tr>
              <td colspan="2" style="padding:20px 16px;border-top:1px solid #e5e5e5;">
                <div style="font-size:10px;letter-spacing:0.25em;text-transform:uppercase;color:#6b7280;font-weight:600;">${labels.threeYear}</div>
                <div style="margin-top:8px;font-size:28px;font-weight:900;color:#000;">${money(metrics.threeYearSavings)}</div>
              </td>
            </tr>
          </table>
        </td></tr>

        <tr><td style="padding:0 32px 16px;">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
            <tr>
              <td width="50%" style="padding-right:8px;vertical-align:top;">
                <div style="border:1px solid #e5e5e5;border-radius:8px;padding:16px;">
                  <div style="font-size:10px;letter-spacing:0.25em;text-transform:uppercase;color:#6b7280;font-weight:600;">${labels.implementation}</div>
                  <div style="margin-top:8px;font-size:18px;font-weight:700;color:#000;">${money(metrics.implementationCostLow)} – ${money(metrics.implementationCostHigh)}</div>
                </div>
              </td>
              <td width="50%" style="padding-left:8px;vertical-align:top;">
                <div style="border:1px solid #e5e5e5;border-radius:8px;padding:16px;">
                  <div style="font-size:10px;letter-spacing:0.25em;text-transform:uppercase;color:#6b7280;font-weight:600;">${labels.payback}</div>
                  <div style="margin-top:8px;font-size:18px;font-weight:700;color:#000;">${metrics.paybackMonths ? `${metrics.paybackMonths} ${labels.paybackMonths}` : '—'}</div>
                </div>
              </td>
            </tr>
          </table>
        </td></tr>

        <tr><td style="padding:16px 32px;">
          <div style="font-size:10px;letter-spacing:0.25em;text-transform:uppercase;color:#6b7280;font-weight:600;">${labels.readiness}</div>
          <div style="margin:8px 0 6px;height:6px;background:#e5e5e5;border-radius:999px;overflow:hidden;">
            <div style="height:100%;width:${readinessPct}%;background:#000;"></div>
          </div>
          <div style="font-size:14px;font-weight:700;color:#000;">${readinessPct}%</div>
        </td></tr>

        <tr><td style="padding:24px 32px 8px;border-top:1px solid #e5e5e5;">
          <p style="margin:0 0 16px;font-size:16px;line-height:1.6;color:#111;">${escapeHtml(summary.summary)}</p>
        </td></tr>

        <tr><td style="padding:8px 32px;">
          <div style="font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:#6b7280;font-weight:600;margin-bottom:12px;">${labels.focus}</div>
          <ol style="margin:0 0 16px;padding-left:20px;color:#1f2937;font-size:14px;line-height:1.7;">
            ${summary.bulletPoints.map(p => `<li style="margin-bottom:6px;">${escapeHtml(p)}</li>`).join('')}
          </ol>
        </td></tr>

        ${summary.quickWins && summary.quickWins.length > 0 ? `
        <tr><td style="padding:8px 32px;">
          <div style="font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:#6b7280;font-weight:600;margin-bottom:12px;">${labels.quickWins}</div>
          <ul style="list-style:none;margin:0 0 16px;padding:0;">
            ${summary.quickWins.map(w => `<li style="border-left:3px solid #000;padding:4px 0 4px 12px;margin-bottom:10px;color:#1f2937;font-size:14px;line-height:1.6;">${escapeHtml(w)}</li>`).join('')}
          </ul>
        </td></tr>` : ''}

        <tr><td style="padding:32px;">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#000;border-radius:8px;">
            <tr><td style="padding:28px;color:#fff;">
              <div style="font-size:22px;font-weight:900;">${labels.ctaTitle}</div>
              <div style="margin-top:8px;color:rgba(255,255,255,0.7);font-size:15px;line-height:1.55;">${labels.ctaBody}</div>
              <div style="margin-top:20px;">
                <a href="https://wazalab.mx/${locale}/contact" style="display:inline-block;background:#fff;color:#000;font-weight:600;padding:12px 20px;border-radius:8px;text-decoration:none;font-size:14px;">${labels.ctaButton} →</a>
              </div>
            </td></tr>
          </table>
        </td></tr>

        <tr><td style="padding:16px 32px 32px;color:#9ca3af;font-size:12px;line-height:1.6;border-top:1px solid #e5e5e5;">
          ${labels.footer}<br>
          ${escapeHtml(context.industry)} · ${escapeHtml(context.country ?? '—')} · ${context.employeeCount} · ${escapeHtml(email)}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;
}

function escapeHtml(s: string) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

async function persistLead(body: SendReportBody): Promise<{ id: string | null; stored: boolean }> {
  const supabase = getSupabaseAdmin();
  if (!supabase) {
    console.warn('[send-report] Supabase env not set — lead will not be stored.');
    return { id: null, stored: false };
  }

  const { data, error } = await supabase
    .from('calculator_leads')
    .insert({
      email: body.email,
      locale: body.locale,
      industry: body.context.industry,
      country: body.context.country,
      employee_count: body.context.employeeCount,
      average_salary: body.context.averageSalary,
      weekly_hours: body.context.weeklyHours,
      ai_maturity: body.context.aiMaturity,
      primary_goal: body.context.primaryGoal,
      annual_hours_saved: body.metrics.annualHoursSaved,
      annual_labor_savings: body.metrics.annualLaborSavings,
      three_year_savings: body.metrics.threeYearSavings,
      implementation_cost_low: body.metrics.implementationCostLow,
      implementation_cost_high: body.metrics.implementationCostHigh,
      payback_months: body.metrics.paybackMonths,
      readiness_score: body.metrics.totalReadinessScore,
      max_readiness_score: body.metrics.maxReadinessScore,
      summary: body.summary,
    })
    .select('id')
    .single();

  if (error) {
    console.error('[send-report] Supabase insert error:', error.message);
    return { id: null, stored: false };
  }

  return { id: data?.id ?? null, stored: true };
}

async function markDelivered(leadId: string, emailId: string | null) {
  const supabase = getSupabaseAdmin();
  if (!supabase) return;
  await supabase
    .from('calculator_leads')
    .update({ email_delivered: true, email_id: emailId })
    .eq('id', leadId);
}

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as SendReportBody;

    if (!body.email || !/\S+@\S+\.\S+/.test(body.email)) {
      return NextResponse.json({ error: 'Invalid email' }, { status: 400 });
    }

    // 1. Persist the lead first — we never want to drop a submission even if email fails.
    const lead = await persistLead(body);

    // 2. Send the email (if Resend is configured).
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      console.warn('[send-report] RESEND_API_KEY is not set — lead stored but email not delivered.');
      return NextResponse.json({ delivered: false, reason: 'email_disabled', stored: lead.stored, leadId: lead.id });
    }

    const subject = body.locale === 'es'
      ? 'Tu reporte de preparación para IA · WAZA'
      : body.locale === 'de'
        ? 'Ihr KI-Bereitschaftsbericht · WAZA'
        : 'Your AI Readiness Report · WAZA';

    const resend = new Resend(apiKey);
    const { data, error } = await resend.emails.send({
      from: FROM,
      to: body.email,
      subject,
      html: renderHtml(body),
      replyTo: REPLY_TO,
    });

    if (error) {
      console.error('[send-report] Resend error:', error);
      return NextResponse.json({ delivered: false, reason: 'resend_error', stored: lead.stored, leadId: lead.id }, { status: 502 });
    }

    if (lead.id) {
      await markDelivered(lead.id, data?.id ?? null);
    }

    console.log('[send-report] Sent to', body.email, '| resend id:', data?.id, '| lead id:', lead.id);
    return NextResponse.json({ delivered: true, id: data?.id, stored: lead.stored, leadId: lead.id });
  } catch (error) {
    console.error('[send-report] Unexpected error:', error);
    return NextResponse.json({ delivered: false, reason: 'unexpected' }, { status: 500 });
  }
}
